import simpy
import numpy as np
import time

class one_dric:
    '''
    many trains are generated by one control point,
    here I want to output the schedule of each train.
    '''

    def __init__(self, begin):
        self.all_schedule = {}
        self.begin = begin
        env = simpy.Environment()
        env.process(self.train(env))
        env.run(until=1000)

    def train(self, env):
        begin_ticks = 0
        #begin_ticks = time.mktime(time.strptime(self.begin, "%Y-%m-%d %H:%M:%S"))
        time_ticks = begin_ticks
        number = 1
        one_schedule = {}
        one_detail = {}
        speed = {}
        distance = {}
        time = {}
        # n is used for create many "one_detail", otherwise all "one_schedule" will be the same
        n = 0

        while True:
            np.random.seed()
            time[number] = 0
            speed[number] = int(np.random.normal(3, 1)) # 180 miles per second
            headway = int(np.random.normal(15, 3))
            time_standard = number # waiting to change
            #time_standard = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time_ticks))
            self.all_schedule[number] = {}

            for i in xrange(1, number+1):
                one_detail[n] = {}
                time[i] += headway * 60
                distance[i] = speed[i] * time[i]
                if i > 1:
                    if distance[i] > distance[i-1] - speed[i-1] * 3 * 60:
                        distance[i] = distance[i-1] - speed[i-1] * 3 * 60
                one_detail[n]['speed'] = speed[i]
                one_detail[n]['distance'] = distance[i]
                one_detail[n]['headway'] = headway
                one_schedule[time_standard] = one_detail[n]
                self.all_schedule[i][time_standard] = one_schedule[time_standard]
                n += 1
            number += 1

            yield env.timeout(headway * 60)

    def genetate_all(self):
        return self.all_schedule




